import { createClient } from "https://esm.sh/@supabase/supabase-js@2.89.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function generateFeatureContent(scenario: any, companyName: string): string {
  const userTags = (scenario.tags as string[]).map((tag: string) => `@${tag}`).join(" ");
  const qa4Tag = `@qa4:${scenario.id}`;
  const allTags = [qa4Tag, userTags].filter(Boolean).join(" ");

  const given = (scenario.given_steps as string[]).map((step: string, i: number) =>
    `    ${i === 0 ? "Given" : "And"} ${step}`
  ).join("\n");
  const when = (scenario.when_steps as string[]).map((step: string, i: number) =>
    `    ${i === 0 ? "When" : "And"} ${step}`
  ).join("\n");
  const then = (scenario.then_steps as string[]).map((step: string, i: number) =>
    `    ${i === 0 ? "Then" : "And"} ${step}`
  ).join("\n");

  return `# 4QA Scenario — do not edit this file manually
# Company: ${companyName}
# Status: ${scenario.status}

${allTags}
Feature: ${scenario.feature}

  Scenario: ${scenario.title}
${given}
${when}
${then}
`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const apiKey = url.searchParams.get("api_key");

    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: "api_key query parameter is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { data: company, error: companyError } = await supabase
      .from("companies")
      .select("id, name")
      .eq("api_key", apiKey)
      .single();

    if (companyError || !company) {
      return new Response(
        JSON.stringify({ error: "Invalid API key" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { data: scenarios, error: scenariosError } = await supabase
      .from("scenarios")
      .select("*")
      .eq("company_id", company.id);

    if (scenariosError) {
      return new Response(
        JSON.stringify({ error: "Failed to fetch scenarios" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const features = (scenarios || []).map((scenario: any) => {
      const featureSlug = scenario.feature.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
      const titleSlug = scenario.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
      const path = `cypress/e2e/features/${featureSlug}/${titleSlug}.feature`;

      return {
        id: scenario.id,
        path,
        content: generateFeatureContent(scenario, company.name),
        feature: scenario.feature,
        title: scenario.title,
        status: scenario.status,
        priority: scenario.priority,
        tags: scenario.tags,
      };
    });

    // map by file path: { "path/to/file.feature": "uuid" }  — for Cucumber/plugin usage
    const map: Record<string, string> = {};
    for (const f of features) {
      map[f.path] = f.id;
    }

    // titleMap: { "Scenario title": "uuid" } — for plain Cypress usage
    const titleMap: Record<string, string> = {};
    for (const s of (scenarios || [])) {
      titleMap[s.title] = s.id;
    }

    return new Response(
      JSON.stringify({
        company: company.name,
        total: features.length,
        features,
        map,
        titleMap,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
